// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umfmrdrhqyrvclhfunzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZm1yZHJocXlydmNsaGZ1bnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTc4ODcsImV4cCI6MjA3MDEzMzg4N30.11hJ7Py2DZNgxepq_RkV8agHriSLMJYrIwHjndWhL7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});